ALTER TABLESPACE MCN_CALL2
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL22.dbf' SIZE 1285M;

ALTER TABLESPACE MCN_CALL3
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL32.dbf' SIZE 1350M;

ALTER TABLESPACE MCN_CALL4
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL42.dbf' SIZE 771M;

ALTER TABLESPACE MCN_CALL5
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL52.dbf' SIZE 1350M;

ALTER TABLESPACE MCN_CALL6
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL62.dbf' SIZE 1415M;

ALTER TABLESPACE MCN_CALL7
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL72.dbf' SIZE 4275M;

ALTER TABLESPACE MCN_CALL8
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL82.dbf' SIZE 4275M;

ALTER TABLESPACE MCN_CALL9
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL92.dbf' SIZE 2715M;

ALTER TABLESPACE MCN_CALL3
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL32.dbf' SIZE 1350M;

ALTER TABLESPACE MCN_CALL_IND2
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND22.dbf' SIZE 1485M;

ALTER TABLESPACE MCN_CALL_IND3
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND32.dbf' SIZE 1366M;

ALTER TABLESPACE MCN_CALL_IND4
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND42.dbf' SIZE 917M;

ALTER TABLESPACE MCN_CALL_IND5
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND52.dbf' SIZE 1592M;

ALTER TABLESPACE MCN_CALL_IND6
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND62.dbf' SIZE 1633M;

ALTER TABLESPACE MCN_CALL_IND7
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND72.dbf' SIZE 1633M;

ALTER TABLESPACE MCN_CALL_IND8
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND82.dbf' SIZE 2752M;

ALTER TABLESPACE MCN_CALL_IND9
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_IND92.dbf' SIZE 2671M;

ALTER TABLESPACE MCN_CALL_LOG_P1
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_CALL_LOG_P12.dbf' SIZE 9897M;

ALTER TABLESPACE MCN_IDP_LOG
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_IDP_LOG2.dbf' SIZE 2000M;

ALTER TABLESPACE MCN_MISS0
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_MISS02.dbf' SIZE 858M;

ALTER TABLESPACE MCN_MISS1
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_MISS12.dbf' SIZE 858M;

ALTER TABLESPACE MCN_MISS2
ADD TEMPFILE '/oracle1/oradata/music/mcnlog/MCN_MISS22.dbf' SIZE 858M;













